; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.22816.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
PUBLIC	??$square@H@@YAHH@Z				; square<int>
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+43
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
; Function compile flags: /Odtp
; File c:\development\visual\1일차\2일차_01_template_basic\1_template_basic2.cpp
;	COMDAT ??$square@H@@YAHH@Z
_TEXT	SEGMENT
a$ = 8
??$square@H@@YAHH@Z PROC				; square<int>, COMDAT

; 3    : template<typename T> T square(T a) {

	mov	DWORD PTR [rsp+8], ecx

; 4    : 	return a * a;

	mov	eax, DWORD PTR a$[rsp]
	imul	eax, DWORD PTR a$[rsp]

; 5    : }

	ret	0
??$square@H@@YAHH@Z ENDP				; square<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\development\visual\1일차\2일차_01_template_basic\1_template_basic2.cpp
_TEXT	SEGMENT
s$ = 32
main	PROC

; 7    : int main(){

$LN3:
	sub	rsp, 56					; 00000038H

; 8    : 	short s = 3;

	mov	eax, 3
	mov	WORD PTR s$[rsp], ax

; 9    : 
; 10   : 	square(3); // int 버전

	mov	ecx, 3
	call	??$square@H@@YAHH@Z			; square<int>

; 11   : 	// square(s); // short 버전
; 12   : 	square<int>(s);

	movsx	eax, WORD PTR s$[rsp]
	mov	ecx, eax
	call	??$square@H@@YAHH@Z			; square<int>

; 13   : }

	xor	eax, eax
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
END
